#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  int N, A[100], K;

  cin >> N;
  for (int i = 0; i < N; i++) {
    cin >> A[i];
  }
  cin >> K;

  int ans = 0;
  for (int i = 0; i < N; i++) {
    if (K <= A[i]) {
      ans++;
    }
  }

  cout << ans << endl;

  return 0;
}
